### PR TITLE
update Ro16 results and QF matchups

### PR DESCRIPTION
**Pull request by stvhwrd**
Round of 16 complete, quarterfinal matchups set.

### CODE REVIEW

**Comment by geraldb** [comment]
@stvhwrd Thanks for the Round of 16 updates. Let me know if interested and I send you an invitation (via GitHub) to join the editors team (so can change/update directly in the browser or commit without pull request). Cheers.

**Comment by stvhwrd** [comment]
@geraldb Thank you for the offer, I'd like to join the team!

**Comment by geraldb** [comment]
@stvhwrd  Welcome to the football.db team. Tried to add you to the euro-cup repo - not sure if GitHub worked - the invitation by email via GitHub should be on its way. Will try to send out another invitation later today. Keep it up. Cheers.

**Comment by geraldb** [comment]
@stvhwrd  Welcome. FYI: In the [/openfootball/people page](https://github.com/orgs/openfootball/people) you can set your membership to public (default is private). Cheers.  PS: Will try to add a datefile for auto-builds and imports later this week.

**Comment by stvhwrd** [comment]
Thanks @geraldb!  Are there any places I can see this data being used?  Webapps or online DB's or anything I can check out?

**Comment by geraldb** [comment]
Helllo @stvhwrd Good questions. Please send the question to the [forum / mailing list](https://groups.google.com/group/opensport). Happy to answer. There's nobody here (on GitHub issues) ;-)  Others can join the converstation (in theory) on the forum. Thanks. Cheers.

**Pull request merged**
